# Generated by Django 3.1.7 on 2021-04-20 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=50, verbose_name='Industry')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Buying Price'),
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quality',
            field=models.IntegerField(default=0, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
