# Generated by Django 3.1.7 on 2021-04-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210330_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Buying Price'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quality',
            field=models.IntegerField(default=0, verbose_name='Quality'),
        ),
    ]
