# Generated by Django 3.1.7 on 2021-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210401_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Profit'),
        ),
    ]
