# Generated by Django 3.1.7 on 2021-04-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_portfolio_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='portfoilo',
            new_name='portfolio',
        ),
    ]
