# Generated by Django 3.1.7 on 2021-04-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210405_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio', verbose_name='Portfolio'),
        ),
    ]
