# Generated by Django 3.1.7 on 2021-04-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20210406_0045'),
        ('stocks', '0004_stock_profit'),
    ]

    operations = [
    ]
